# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7077a844178d0b350452d106cc7260987b9ee8b1fe0bc3c69f9ec0c721a6b71844d2f98052dae1a23eb935961d030e337f234c0be61bda3db58016be9bce46

test:
  secret_key_base: 28c02f1242c23758a0c3341adc12708ee5b781fbec297c3957523b2734dca7ba188de832f994fb515decefd7569c45a80c4a09dafa4331d9f0b6574fc49d3955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
